name: Deploy Storage Account
on: [push]
jobs: 
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout IaC
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: e2b5a834-44ee-48a3-866d-dc106a68e0dc
          resourceGroupName: exampleRG
          template: ./StorageAccount/main.bicep
          failOnStdErr: false
